# -*- coding: utf-8 -*-
"""Dowry Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SAWejHS-bY_ppZ2ssf9QneZVE-CFgeRl
"""

# 🧠 Dowry Calculator - Just for Fun 😄
print("💍 Welcome to the Fun Dowry Calculator 💰 (Parody Project)")
print("-----------------------------------------------------------")

# Taking user inputs
name = input("Enter your name: ")
age = int(input("Enter your age: "))
degree = input("Your highest degree (BTech / MTech / PhD / Dropout): ")
college = input("College tier (Tier 1 / Tier 2 / Tier 3 / Local): ")
job = input("Job role (None / Software Dev / AI Engineer / Govt Officer): ")
salary = int(input("Annual Salary in Lakhs ₹: "))
height = int(input("Your height in cm (Just for fun): "))
skills = input("Special skills (Cooks / Codes / Sings / None): ")
looks = int(input("Self-rated looks (1 to 10): "))

print("\nThanks! Calculating your ideal fun dowry demand... 😂")

# 💰 Start with a base dowry value
dowry = 5  # in Lakhs

# 🎓 Degree bonus
if degree == "PhD":
    dowry += 20
elif degree == "MTech":
    dowry += 15
elif degree == "BTech":
    dowry += 10
elif degree == "Dropout":
    dowry -= 5

# 🏫 College tier bonus
if college == "Tier 1":
    dowry += 10
elif college == "Tier 2":
    dowry += 5
elif college == "Tier 3":
    dowry += 2
else:
    dowry -= 2

# 💼 Job bonus
if job == "AI Engineer":
    dowry += 15
elif job == "Software Dev":
    dowry += 10
elif job == "Govt Officer":
    dowry += 20
elif job == "None":
    dowry -= 5

# 💸 Salary bonus
dowry += salary * 0.8  # 80% of salary added as bonus

# 📏 Height bonus (just for laughs 😄)
if height > 180:
    dowry += 5
elif height < 160:
    dowry -= 2

# 🛠 Skills bonus
if "Cooks" in skills:
    dowry += 5
if "Codes" in skills:
    dowry += 5
if "Sings" in skills:
    dowry += 3

# 😎 Looks bonus
dowry += looks * 1.5

# 🧮 Final result
dowry = round(dowry, 2)

# 🎉 Display the final funny output
print("-----------------------------------------------------------")
print(f"🎩 Hello {name}, based on your elite profile 🤓...")
print(f"💰 Your ideal *dowry demand* is: ₹{dowry} Lakhs! 💸")

# Funny bonus comments
if dowry > 60:
    print("🏆 You're premium! Time to ask for gold-plated horses too.")
elif dowry > 40:
    print("🔥 Solid profile! Aunties will be fighting over you.")
elif dowry > 20:
    print("😎 Respectable! But work on your cooking skills maybe?")
else:
    print("🤣 Hmm... maybe you should give dowry instead. Just kidding!")

# 📢 Disclaimers
print("\n⚠️ Disclaimer: This project is purely for fun and educational purposes.")
print("🚫 Say NO to dowry in real life. Support equality and love 💛")
print("-----------------------------------------------------------")
